In [1]:
import ptan
import numpy as np

In [2]:
q_vals = np.array([[1, 2, 3], [1, -1, 0]])
print("q_vals")
print(q_vals)

q_vals
[[ 1  2  3]
 [ 1 -1  0]]


In [3]:
selector = ptan.actions.ArgmaxActionSelector()
print("argmax:", selector(q_vals))

argmax: [2 0]


In [4]:
selector = ptan.actions.EpsilonGreedyActionSelector()
print("epsilon=0.0:", selector(q_vals))

epsilon=0.0: [2 0]


In [5]:
selector.epsilon = 1.0
print("epsilon=1.0:", selector(q_vals))

epsilon=1.0: [1 2]


In [6]:
selector.epsilon = 0.5
print("epsilon=0.5:", selector(q_vals))

epsilon=0.5: [1 0]


In [7]:
selector.epsilon = 0.1
print("epsilon=0.1:", selector(q_vals))

epsilon=0.1: [2 0]


In [8]:
selector = ptan.actions.ProbabilityActionSelector()
print("Actions sampled from three prob distributions:")
for _ in range(10):
    acts = selector(np.array([
        [0.1, 0.8, 0.1],
        [0.0, 0.0, 1.0],
        [0.5, 0.5, 0.0]
    ]))
    print(acts)

Actions sampled from three prob distributions:
[0 2 1]
[0 2 0]
[1 2 1]
[1 2 0]
[1 2 1]
[1 2 1]
[1 2 1]
[1 2 1]
[1 2 0]
[1 2 0]
