In [1]:
import ptan
import torch.nn as nn

In [2]:
class DQNNet(nn.Module):
    def __init__(self):
        super(DQNNet, self).__init__()
        self.ff = nn.Linear(5, 3)
        
    def forward(self, x):
        return self.ff(x)

In [7]:
net = DQNNet()
print(net)

DQNNet(
  (ff): Linear(in_features=5, out_features=3, bias=True)
)


In [8]:
tgt_net = ptan.agent.TargetNet(net)
print("Main net:", net.ff.weight)
print("Target net:", tgt_net.target_model.ff.weight)

Main net: Parameter containing:
tensor([[ 0.3669, -0.0879, -0.0668, -0.1215,  0.3779],
        [-0.4396,  0.2070,  0.3378,  0.3044,  0.3197],
        [ 0.4045, -0.1415, -0.0235, -0.3957, -0.0357]], requires_grad=True)
Target net: Parameter containing:
tensor([[ 0.3669, -0.0879, -0.0668, -0.1215,  0.3779],
        [-0.4396,  0.2070,  0.3378,  0.3044,  0.3197],
        [ 0.4045, -0.1415, -0.0235, -0.3957, -0.0357]], requires_grad=True)


In [9]:
net.ff.weight.data += 1.0
print("After update")
print("Main net:", net.ff.weight)
print("Target net:", tgt_net.target_model.ff.weight)

After update
Main net: Parameter containing:
tensor([[1.3669, 0.9121, 0.9332, 0.8785, 1.3779],
        [0.5604, 1.2070, 1.3378, 1.3044, 1.3197],
        [1.4045, 0.8585, 0.9765, 0.6043, 0.9643]], requires_grad=True)
Target net: Parameter containing:
tensor([[ 0.3669, -0.0879, -0.0668, -0.1215,  0.3779],
        [-0.4396,  0.2070,  0.3378,  0.3044,  0.3197],
        [ 0.4045, -0.1415, -0.0235, -0.3957, -0.0357]], requires_grad=True)


In [10]:
tgt_net.sync()
print("After sync")
print("Main net:", net.ff.weight)
print("Target net:", tgt_net.target_model.ff.weight)

After sync
Main net: Parameter containing:
tensor([[1.3669, 0.9121, 0.9332, 0.8785, 1.3779],
        [0.5604, 1.2070, 1.3378, 1.3044, 1.3197],
        [1.4045, 0.8585, 0.9765, 0.6043, 0.9643]], requires_grad=True)
Target net: Parameter containing:
tensor([[1.3669, 0.9121, 0.9332, 0.8785, 1.3779],
        [0.5604, 1.2070, 1.3378, 1.3044, 1.3197],
        [1.4045, 0.8585, 0.9765, 0.6043, 0.9643]], requires_grad=True)
